import Foundation

/// Chat session — the heart of D-Rats interactive messaging.
///
/// Ported from `d_rats.sessions.chat.ChatSession`. Handles six frame
/// sub-types on the wire, defined in upstream as:
///
/// ```
/// T_DEF      = 0   // plain chat message (or embedded GPS fix)
/// T_PNG_REQ  = 1   // ping request
/// T_PNG_RSP  = 2   // ping response (carries free-form reply text)
/// T_PNG_ERQ  = 3   // ping echo request (round-trip data integrity test)
/// T_PNG_ERS  = 4   // ping echo response
/// T_STATUS   = 5   // station status broadcast ("<digit><message>")
/// ```
///
/// ChatSession is stateless at the wire level — each message is a single
/// DDT2 frame with no pairing or retries. State machines like file
/// transfer use `StatefulSession` (v1.1+).
///
/// MacRats sets `compress = false` for chat frames, matching upstream
/// behavior. Chat messages are typically tiny and the zlib overhead
/// exceeds the savings.
public final class ChatSession: StatelessSession, @unchecked Sendable {

    // MARK: - Frame sub-types (must match upstream)

    public static let T_DEF:     UInt8 = 0
    public static let T_PNG_REQ: UInt8 = 1
    public static let T_PNG_RSP: UInt8 = 2
    public static let T_PNG_ERQ: UInt8 = 3
    public static let T_PNG_ERS: UInt8 = 4
    public static let T_STATUS:  UInt8 = 5

    // MARK: - Events

    /// Delegate protocol for the chat UI (SwiftUI app layer). All
    /// callbacks run on the session manager's queue; the delegate is
    /// responsible for hopping to main-actor if it needs to.
    public protocol Delegate: AnyObject, Sendable {
        func chatSession(_ session: ChatSession, didReceiveMessage text: String, from sStation: String, to dStation: String)
        func chatSession(_ session: ChatSession, didReceivePingRequest from: String, to dStation: String)
        func chatSession(_ session: ChatSession, didReceivePingResponse from: String, to dStation: String, replyText: String)
        func chatSession(_ session: ChatSession, didReceiveEchoRequest from: String, to dStation: String, payload: Data)
        func chatSession(_ session: ChatSession, didReceiveEchoResponse from: String, to dStation: String, payload: Data)
        func chatSession(_ session: ChatSession, didReceiveStationStatus from: String, status: StationStatus, message: String)
    }

    /// Default delegate implementations so apps only need to override the
    /// methods they care about.
    public static func noopDelegate() -> Delegate { NoopChatDelegate() }

    public weak var delegate: Delegate?

    // MARK: - Ping reply text

    /// Text returned in ping responses. Defaults to "Running MacRats <version>".
    /// The upstream value is generated by `ping_data()` on every ping reply;
    /// we cache it and let the app override it from the config sheet.
    public var pingReplyText: String

    /// Current station status (broadcast in reply to pings via
    /// `advertise(status:message:)`).
    public var currentStatus: StationStatus = .online

    /// Current status message (free-form text broadcast with status).
    public var currentStatusMessage: String = ""

    // MARK: - Init

    public init(name: String = "chat", pingReplyText: String = "Running MacRats") {
        self.pingReplyText = pingReplyText
        super.init(name: name)
        self.compress = false
        self.defaultFrameType = Self.T_DEF
    }

    // MARK: - Outbound API

    /// Send a chat message to a destination (CQCQCQ by default for broadcast).
    public func sendMessage(_ text: String, to dest: String = "CQCQCQ") throws {
        try write(text, dest: dest)
    }

    /// Send a ping request to another station.
    public func pingStation(_ station: String) throws {
        try send(frameType: Self.T_PNG_REQ,
                 data: Data("Ping Request".utf8),
                 dest: station)
    }

    /// Send a ping echo request. The remote station will return the same
    /// payload in a T_PNG_ERS frame, letting us verify round-trip data
    /// integrity.
    public func pingEchoStation(_ station: String, data: Data) throws {
        try send(frameType: Self.T_PNG_ERQ, data: data, dest: station)
    }

    /// Broadcast a station status update. This is normally called
    /// automatically after replying to a ping, but can also be called
    /// explicitly from the UI when the user changes their status.
    public func advertise(status: StationStatus, message: String) throws {
        // Wire format: "<digit><message>" where <digit> is the status code
        // as an ASCII digit and <message> is the free-form status text.
        let prefix = String(status.rawValue)
        let combined = prefix + message
        try send(frameType: Self.T_STATUS,
                 data: Data(combined.utf8),
                 dest: "CQCQCQ")
    }

    /// Convenience — send status using the cached current values.
    public func advertiseCurrentStatus() throws {
        try advertise(status: currentStatus, message: currentStatusMessage)
    }

    // MARK: - Inbound

    /// Override StatelessSession.incomingData to interpret the 6 chat
    /// frame sub-types.
    public override func incomingData(_ frame: DDT2Frame) {
        switch frame.type {
        case Self.T_DEF:
            handleDefault(frame)
        case Self.T_PNG_REQ:
            handlePingRequest(frame)
        case Self.T_PNG_RSP:
            handlePingResponse(frame)
        case Self.T_PNG_ERQ:
            handleEchoRequest(frame)
        case Self.T_PNG_ERS:
            handleEchoResponse(frame)
        case Self.T_STATUS:
            handleStationStatus(frame)
        default:
            // Unknown chat sub-type — surface through the generic handler
            // in case the app wants to log it.
            handler?(frame)
        }
    }

    private func handleDefault(_ frame: DDT2Frame) {
        // Upstream attempts to parse the payload as a GPS fix first via
        // `gps.parse_gps(frame_data)`. If it's a valid fix, it emits
        // `incoming-gps-fix`. Otherwise it's a chat message. We defer GPS
        // parsing to a later session (it's its own large port from
        // `d_rats/gps.py`); for now everything in T_DEF goes through as a
        // plain message.
        let text = String(decoding: frame.data, as: UTF8.self)
        delegate?.chatSession(self,
                              didReceiveMessage: text,
                              from: frame.sStation,
                              to: frame.dStation)
    }

    private func handlePingRequest(_ frame: DDT2Frame) {
        // Fire the event regardless of who the ping was for — the UI may
        // want to log broadcast pings.
        delegate?.chatSession(self,
                              didReceivePingRequest: frame.sStation,
                              to: frame.dStation)

        // Respond if the ping was directed at us or broadcast to CQCQCQ.
        guard let manager else { return }
        let isBroadcast = frame.dStation == "CQCQCQ"
        let isForUs = frame.dStation == manager.callsign
        guard isBroadcast || isForUs else { return }

        // Upstream waits a random 0..5.0 second delay before replying to
        // broadcast pings to avoid everyone on frequency replying at once.
        // We preserve that behavior.
        let delaySeconds: TimeInterval = isBroadcast ? Double.random(in: 0...5) : 0
        let replyText = pingReplyText
        manager.scheduleAfter(delaySeconds) { [weak self] in
            guard let self else { return }
            do {
                try self.send(frameType: Self.T_PNG_RSP,
                              data: Data(replyText.utf8),
                              dest: frame.sStation)
                // Also broadcast our current status — upstream does this
                // right after replying to a ping.
                try? self.advertiseCurrentStatus()
            } catch {
                // Session probably got closed during the delay; nothing
                // actionable here. Log via the manager.
                self.manager?.log("chat ping-reply failed: \(error.localizedDescription)")
            }
        }
    }

    private func handlePingResponse(_ frame: DDT2Frame) {
        let text = String(decoding: frame.data, as: UTF8.self)
        delegate?.chatSession(self,
                              didReceivePingResponse: frame.sStation,
                              to: frame.dStation,
                              replyText: text)
    }

    private func handleEchoRequest(_ frame: DDT2Frame) {
        delegate?.chatSession(self,
                              didReceiveEchoRequest: frame.sStation,
                              to: frame.dStation,
                              payload: frame.data)

        guard let manager else { return }
        let isBroadcast = frame.dStation == "CQCQCQ"
        let isForUs = frame.dStation == manager.callsign
        guard isBroadcast || isForUs else { return }

        // Upstream uses a 0..10 second random delay for broadcast echo
        // requests (twice the ping-request delay, because echo replies
        // are larger and more likely to collide).
        let delaySeconds: TimeInterval = isBroadcast ? Double.random(in: 0...10) : 0
        let echoPayload = frame.data
        let dest = frame.sStation
        manager.scheduleAfter(delaySeconds) { [weak self] in
            guard let self else { return }
            do {
                try self.send(frameType: Self.T_PNG_ERS, data: echoPayload, dest: dest)
            } catch {
                self.manager?.log("chat echo-reply failed: \(error.localizedDescription)")
            }
        }
    }

    private func handleEchoResponse(_ frame: DDT2Frame) {
        delegate?.chatSession(self,
                              didReceiveEchoResponse: frame.sStation,
                              to: frame.dStation,
                              payload: frame.data)
    }

    private func handleStationStatus(_ frame: DDT2Frame) {
        guard let firstByte = frame.data.first else { return }
        // Wire format: first byte is ASCII digit '0'..'9', rest is message.
        let zero = UInt8(ascii: "0")
        let nine = UInt8(ascii: "9")
        guard firstByte >= zero && firstByte <= nine else { return }
        let rawStatus = Int(firstByte - zero)
        let status = StationStatus(rawValue: rawStatus) ?? .unknown
        let messageBytes = frame.data.dropFirst()
        let message = String(decoding: messageBytes, as: UTF8.self)
        delegate?.chatSession(self,
                              didReceiveStationStatus: frame.sStation,
                              status: status,
                              message: message)
    }
}

// MARK: - No-op delegate for tests / early-adopter apps

private final class NoopChatDelegate: ChatSession.Delegate, @unchecked Sendable {
    func chatSession(_ session: ChatSession, didReceiveMessage text: String, from sStation: String, to dStation: String) {}
    func chatSession(_ session: ChatSession, didReceivePingRequest from: String, to dStation: String) {}
    func chatSession(_ session: ChatSession, didReceivePingResponse from: String, to dStation: String, replyText: String) {}
    func chatSession(_ session: ChatSession, didReceiveEchoRequest from: String, to dStation: String, payload: Data) {}
    func chatSession(_ session: ChatSession, didReceiveEchoResponse from: String, to dStation: String, payload: Data) {}
    func chatSession(_ session: ChatSession, didReceiveStationStatus from: String, status: StationStatus, message: String) {}
}
